<a href="https://colab.research.google.com/github/umiSirya/General-Data-analysis/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise 2

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [2]:
import numpy as np

arr = np.ones((5,5))
arr=np.pad(arr,pad_width=1,mode='constant',constant_values=0)
arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan  
np.nan == np.nan   
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [9]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [16]:
arr =np.diag(1+np.arange(4))
arr





array([[ 1,  2,  3,  4,  5],
       [ 1,  7,  8,  9, 10],
       [11,  1, 13, 14, 15],
       [16, 17,  1, 19, 20],
       [21, 22, 23,  1, 25]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [17]:
arr =np.zeros((8,8))
arr[1::2,::2]=1
arr[::2,1::2]=1

arr


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [19]:
arr==np.unravel_index(100,(6,7,8))
arr

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [20]:
arr =np.zeros((8,8))
arr[1::2,::2]=1
arr[::2,1::2]=1

arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [21]:
arr=np.random.random((5,5))
arr=(arr-np.mean(arr))/np.std(arr)
print(arr)

[[ 0.58824805 -1.77067425 -0.19831316 -0.94099464 -1.19010271]
 [ 0.95304998  1.5767527  -0.03764228 -0.99019698 -0.24209115]
 [ 1.68151196 -0.19729847 -0.79929554  0.1164627  -1.13643783]
 [ 1.49915825  1.00563657 -1.72283053  1.27496545 -1.03709691]
 [-0.11551243  0.56853211  0.55676316  0.59673431 -0.03932835]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [25]:
color_dtype = np.dtype([
    ('red', np.uint8),
    ('green', np.uint8),
    ('blue', np.uint8),
    ('alpha', np.uint8)
])
color_array = np.array([(255, 0, 0, 255)], dtype=color_dtype)  # Red color with full opacity
print(color_array)

[(255, 0, 0, 255)]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [26]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12],
    [13, 14, 15]
])

B = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

C = np.dot(A, B)

# Display the result
print("Matrix A (5x3):")
print(A)
print("\nMatrix B (3x2):")
print(B)
print("\nProduct Matrix C (5x2):")
print(C)


Matrix A (5x3):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

Matrix B (3x2):
[[1 2]
 [3 4]
 [5 6]]

Product Matrix C (5x2):
[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8,

*   List item
*   List item

in place. (★☆☆)

In [3]:

arr = np.array([1, 4, 6, 8, 10, 2, 5, 7])

# Negate elements that are between 3 and 8, inclusive
arr[(arr >= 3) & (arr <= 8)] *= -1

print("Updated array:", arr)


Updated array: [ 1 -4 -6 -8 10  2 -5 -7]


 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [4]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
#The expressions that aren't legal are:Z <- Z & Z < Z > Z

#### 28. What are the result of the following expressions?

1.   List item
2.   List item


```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

In [24]:

float_array = np.array([1.2, -1.2, 2.5, -2.5, 3.7, -3.7])

# Round away from zero
rounded_array = np.copysign(np.ceil(np.abs(float_array)), float_array)
print(rounded_array)


[ 2. -2.  3. -3.  4. -4.]


#### 30. How to find common values between two arrays? (★☆☆)

In [23]:

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

# Find common values
common_values = np.intersect1d(array1, array2)
print(common_values)


[4 5]
