<a href="https://colab.research.google.com/github/umiSirya/General-Data-analysis/blob/main/Numpy1.1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
np.__version__

#### 3. Create a null vector of size 10 (★☆☆)

In [22]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [6]:
arr= np.zeros((5,5))
arr
print(arr.size * arr.itemsize)

200


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [7]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
vector = np.zeros(10)
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
arr= np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
arr = np.arange(10,20)
print(arr)
reversed_vector = arr[::-1]
print(reversed_vector)


[10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [14]:
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_elements = np.nonzero(arr)[0]

non_zero_elements


array([0, 1, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [16]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [17]:
arr=np.random.rand(3,3,3)
arr

array([[[0.37417594, 0.78529532, 0.50187399],
        [0.69387772, 0.30172223, 0.18823454],
        [0.23432148, 0.94830986, 0.86665913]],

       [[0.98978533, 0.11662608, 0.72070583],
        [0.34248785, 0.57545689, 0.96524304],
        [0.34349507, 0.00245179, 0.78816761]],

       [[0.54426202, 0.48128524, 0.26475931],
        [0.95165812, 0.85754952, 0.39345757],
        [0.83111772, 0.72065627, 0.04967318]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [18]:
arr = np.random.rand(10,10)
print(arr)
print(np.min(arr))
print(np.max(arr))

[[5.44396312e-01 7.05666254e-02 1.19774352e-01 7.33941834e-01
  8.01102373e-01 5.30608344e-02 3.29071257e-01 8.83021046e-01
  6.96550580e-01 4.40065017e-01]
 [5.62414359e-01 9.11064766e-01 4.25817273e-01 9.61858604e-01
  7.94866084e-01 1.85185547e-01 8.56139354e-01 6.05829088e-01
  3.46613889e-01 5.67455102e-01]
 [5.85873264e-01 3.94915459e-01 5.86912739e-02 8.59524974e-01
  2.14722148e-01 8.29789252e-02 9.98311371e-01 7.40503066e-01
  7.39870709e-01 7.18348156e-01]
 [6.70735430e-01 8.57962851e-01 9.16354442e-01 8.50237412e-02
  1.46494779e-01 3.45802049e-01 7.80246414e-01 3.45143370e-01
  9.76561280e-01 9.85915401e-01]
 [7.99326781e-01 6.74514197e-01 6.78369410e-01 2.40938106e-01
  2.58004541e-01 6.57992711e-01 2.16142638e-01 7.11179020e-01
  9.44723824e-01 9.98965928e-01]
 [2.83833699e-01 5.74115276e-01 7.94882340e-01 3.76043837e-02
  5.50010146e-01 2.56276130e-02 8.93942504e-01 4.61702540e-01
  9.49352337e-01 7.71385918e-01]
 [3.26307227e-01 6.34176817e-01 5.64659410e-01 1.38626933e

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [19]:
arr =np.random.rand(30)
print(arr)
print(np.mean(arr))

[0.20420538 0.04562022 0.40809168 0.97624416 0.66028049 0.31610319
 0.15885619 0.77178275 0.03527368 0.94914761 0.56992092 0.09138386
 0.59318755 0.65628439 0.45855428 0.77808229 0.52741418 0.94317589
 0.22017667 0.42737334 0.93674749 0.44008434 0.70969738 0.95037409
 0.45909864 0.77092183 0.35718879 0.87906553 0.20998967 0.22282547]
0.5242383988652887


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [21]:
arr=np.ones((5,5))
arr

arr[1:-1, 1:-1] = 0
print(arr)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
