<a href="https://colab.research.google.com/github/umiSirya/General-Data-analysis/blob/main/Numpy3_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise 3

### All of the questions in this exercise are attributed to rougier/numpy-100

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [1]:
import warnings
import numpy as np

# Suppress all warnings
warnings.filterwarnings("ignore")
np.seterr(all='ignore')  # Ignore all NumPy-specific warnings

# Example: Division by zero
array = np.array([1, 2, 0])
result = 1 / array  # Normally this would generate a RuntimeWarning

print("Result:", result)


Result: [1.  0.5 inf]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [4]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [5]:
from datetime import datetime, timedelta

# Get today's date
today = datetime.now().date()

# Calculate yesterday and tomorrow
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2024-11-15
Today: 2024-11-16
Tomorrow: 2024-11-17


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [7]:
from datetime import date, timedelta

# Define the start and end dates for July 2016
start_date = date(2016, 7, 1)
end_date = date(2016, 7, 31)

# Generate all dates in July 2016
current_date = start_date
while current_date <= end_date:
    print(current_date)
    current_date += timedelta(days=1)


2016-07-01
2016-07-02
2016-07-03
2016-07-04
2016-07-05
2016-07-06
2016-07-07
2016-07-08
2016-07-09
2016-07-10
2016-07-11
2016-07-12
2016-07-13
2016-07-14
2016-07-15
2016-07-16
2016-07-17
2016-07-18
2016-07-19
2016-07-20
2016-07-21
2016-07-22
2016-07-23
2016-07-24
2016-07-25
2016-07-26
2016-07-27
2016-07-28
2016-07-29
2016-07-30
2016-07-31


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [8]:
import numpy as np


A = np.array([2.0, 4.0, 6.0])
B = np.array([1.0, 3.0, 5.0])


A /= -2  # Divide A by -2 in place
B += A   # Add A (modified) to B in place
B *= A   # Multiply the result by A (modified) in place

# Result is stored in B
print("Result:", B)

Result: [-0. -2. -6.]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [9]:
random_array = np.random.uniform(0, 100, size=10)  # Array of 10 random numbers between 0 and 100
print("Original Array:", random_array)

# Using np.floor
integer_part_floor = np.floor(random_array).astype(int)
print("Method 1 (np.floor):", integer_part_floor)

Original Array: [56.87409731 21.5029509  36.46907913  6.56640449 13.20439651 14.50124564
 89.53556875 77.86302212  9.23125234 16.34955921]
Method 1 (np.floor): [56 21 36  6 13 14 89 77  9 16]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [10]:
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [11]:
def generate_integers():
    for i in range(10):
        yield i  # Generate integers from 0 to 9

# Use the generator to create a NumPy array
generator = generate_integers()
array = np.fromiter(generator, dtype=int)

print("Generated Array:", array)

Generated Array: [0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [12]:
vector = np.linspace(0, 1, num=12, endpoint=False)[1:-1]  # Exclude 0 and 1
print("Vector:", vector)

Vector: [0.08333333 0.16666667 0.25       0.33333333 0.41666667 0.5
 0.58333333 0.66666667 0.75       0.83333333]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [13]:
random_vector = np.random.rand(10)  # Generates 10 random values in the range [0, 1)

# Sort the vector
sorted_vector = np.sort(random_vector)

print("Random Vector:", random_vector)
print("Sorted Vector:", sorted_vector)

Random Vector: [0.09884708 0.48746069 0.70992582 0.93922717 0.81166417 0.86519394
 0.2514125  0.66113768 0.43266375 0.8277466 ]
Sorted Vector: [0.09884708 0.2514125  0.43266375 0.48746069 0.66113768 0.70992582
 0.81166417 0.8277466  0.86519394 0.93922717]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [14]:
array = np.array([1, 2, 3, 4, 5])


result = sum(array)
print("Sum using built-in sum():", result)

Sum using built-in sum(): 15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [15]:
A = np.random.rand(5)  # Random array of size 5
B = np.random.rand(5)  # Another random array of size 5

# Check if arrays are equal
are_equal = np.array_equal(A, B)

print("Array A:", A)
print("Array B:", B)
print("Are A and B equal?", are_equal)

Array A: [0.32683947 0.40019281 0.80200603 0.05223469 0.45700071]
Array B: [0.54190162 0.41504883 0.7104644  0.11363547 0.45583549]
Are A and B equal? False


#### 43. Make an array immutable (read-only) (★★☆)

In [16]:
array = np.random.rand(5)

# Make the array immutable
array.setflags(write=False)

# Try modifying the array (this will raise an error)
try:
    array[0] = 10  # Attempt to modify the array
except ValueError as e:
    print("Error:", e)

print("Array:", array)

Error: assignment destination is read-only
Array: [0.03937416 0.40204722 0.49650099 0.26281119 0.84433567]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [17]:
# Generate a random 10x2 matrix representing Cartesian coordinates
cartesian_coords = np.random.randn(10, 2)

# Convert Cartesian coordinates to Polar coordinates
r = np.sqrt(cartesian_coords[:, 0]**2 + cartesian_coords[:, 1]**2)  # radius
theta = np.arctan2(cartesian_coords[:, 1], cartesian_coords[:, 0])  # angle

# Stack the results into a 10x2 matrix for polar coordinates
polar_coords = np.column_stack((r, theta))

# Output the Cartesian and Polar coordinates
print("Cartesian Coordinates (x, y):")
print(cartesian_coords)
print("\nPolar Coordinates (r, θ):")
print(polar_coords)

Cartesian Coordinates (x, y):
[[-0.45411279 -0.15606376]
 [ 1.44639872  0.25233228]
 [-1.88837323  0.92667276]
 [ 1.77975242  0.06030279]
 [-1.05530688  0.46096468]
 [ 0.81378263  1.46693614]
 [ 0.36399454  0.33099359]
 [ 0.6693826   0.97057745]
 [-1.64975336 -0.53387705]
 [-0.26688922  0.75416794]]

Polar Coordinates (r, θ):
[[ 0.48018155 -2.81057045]
 [ 1.46824413  0.17271734]
 [ 2.10349135  2.68539219]
 [ 1.78077373  0.03386973]
 [ 1.15159066  2.72976463]
 [ 1.677541    1.0643137 ]
 [ 0.49198454  0.7379496 ]
 [ 1.17902233  0.96703384]
 [ 1.73398698 -2.82861827]
 [ 0.79999946  1.91092855]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [18]:
# Generate a random vector of size 10
random_vector = np.random.randn(10)

# Find the index of the maximum value
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

# Output the result
print("Random Vector with Maximum Value Replaced by 0:")
print(random_vector)

Random Vector with Maximum Value Replaced by 0:
[ 0.         -1.31733975  0.05123976  0.26977022 -0.10360591  0.90813935
 -1.2643179  -1.82646371  0.08735855  0.79193805]
