<a href="https://colab.research.google.com/github/umiSirya/General-Data-analysis/blob/main/Numpy5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise 5

### All of the questions in this exercise are attributed to rougier/numpy-100

In [ ]:
import numpy as np

def find_nearest(array, value):
    array = np.array(array)  # Ensure the input is a numpy array
    idx = (np.abs(array - value)).argmin()  # Find the index of the nearest value
    return array[idx]  # Return the nearest value

# Example usage
array = [10, 22, 14, 26, 34, 45]
value = 20
nearest_value = find_nearest(array, value)
print("Nearest value to", value, "is", nearest_value)

Nearest value to 20 is 22


#### 61. Find the nearest value from a given value in an array (★★☆)

In [ ]:
def find_nearest(array, target):
    # Find the nearest value in the array to the target
    nearest = min(array, key=lambda x: abs(x - target))
    return nearest

# Example usage
array = [10, 22, 14, 26, 34, 45]
target = 20
nearest_value = find_nearest(array, target)
print("Nearest value to", target, "is", nearest_value)


Nearest value to 20 is 22


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [ ]:


# Define the arrays
array1 = np.array([[1, 2, 3]])  # Shape (1, 3)
array2 = np.array([[4], [5], [6]])  # Shape (3, 1)

# Create an iterator to compute the sum element-wise
result = np.empty((3, 3))  # Initialize an empty array to store the results
it = np.nditer([array1,array2, result], flags=['multi_index', 'refs_ok'], op_flags=[['readonly'], ['readonly'], ['writeonly']])

# Perform the element-wise addition using the iterator
for x, y, z in it:
    z[...] = x + y

# Display the result
print("Resultant Array:\n", result)



Resultant Array:
 [[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
class NamedArray:
    def __init__(self, data, name="Unnamed Array"):
        # Initialize with data and name
        self.data = np.array(data)
        self.name = name

    def __repr__(self):
        # Custom representation to display the name and array data
        return f"{self.name}:\n{self.data}"

    def __add__(self, other):
        # Support element-wise addition with another NamedArray or NumPy array
        if isinstance(other, NamedArray):
            other = other.data
        return NamedArray(self.data + other, name=f"{self.name} + {other.name if isinstance(other, NamedArray) else 'Array'}")

    # Add other array-like methods as needed, for example, accessing elements:
    def __getitem__(self, index):
        return self.data[index]

# Example usage
array1 = NamedArray([[1, 2, 3]], name="Array1")
array2 = NamedArray([[4], [5], [6]], name="Array2")

# Print arrays
print(array1)
print(array2)

# Perform addition and print result
result = array1 + array2
print(result)

Array1:
[[1 2 3]]
Array2:
[[4]
 [5]
 [6]]
Array1 + Array:
[[5 6 7]
 [6 7 8]
 [7 8 9]]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [ ]:
vector = np.array([10, 20, 30, 40, 50])
indices = np.array([0, 1, 1, 2, 4])  # Note: index 1 is repeated

# Increment each element in 'vector' at the positions specified by 'indices'
np.add.at(vector, indices, 1)

# Display the result
print("Updated vector:", vector)

Updated vector: [11 22 31 40 51]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
X = np.array([5, 10, 15, 20, 25])  # Values to accumulate
I = np.array([0, 1, 1, 2, 0])      # Index positions in F

# Initialize the target array F with zeros (or another base value if needed)
F = np.zeros(3)

# Accumulate values from X into F at indices specified in I
np.add.at(F, I, X)

# Display the result
print("Accumulated array F:", F)

Accumulated array F: [30. 25. 20.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [ ]:
# Example image with shape (w, h, 3) and dtype=ubyte
# Assuming 'image' is your input image array with shape (w, h, 3)
# For demonstration, let's create a random image
w, h = 100, 100  # Image width and height
image = np.random.randint(0, 256, size=(w, h, 3), dtype=np.uint8)

# Reshape the image to a 2D array of pixels, where each row is a color (R, G, B)
pixels = image.reshape(-1, 3)

# Use np.unique to find unique rows (unique colors), and count them
unique_colors = np.unique(pixels, axis=0)
num_unique_colors = unique_colors.shape[0]

# Display the result
print("Number of unique colors:", num_unique_colors)

Number of unique colors: 9997


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
# Create a sample 4D array
array = np.random.rand(3, 4, 5, 6)  # Shape (3, 4, 5, 6)

# Sum over the last two axes (axis -2 and -1)
result = array.sum(axis=(-2, -1))

# Display the shape and result
print("Shape of the result:", result.shape)
print("Resulting array after summing over the last two axes:\n", result)

Shape of the result: (3, 4)
Resulting array after summing over the last two axes:
 [[14.81200172 12.13530415 13.85613883 14.9914101 ]
 [16.00591366 14.57075353 16.70375084 16.53702427]
 [14.45410455 16.490816   16.5064317  13.59735405]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)